module.exports = {
  apps: [
    {
      name: 'mjn-api',
      cwd: '/var/www/mjn-health/apps/api',
      script: 'node',
      args: 'dist/main.js',
      env_production: { NODE_ENV: 'production', PORT: 3000 },
      instances: 1,
      autorestart: true,
      max_memory_restart: '512M',
    },
    {
      name: 'mjn-web',
      cwd: '/var/www/mjn-health/apps/web',
      script: 'node',
      args: 'node_modules/next/dist/bin/next start -p 3001',
      env_production: { NODE_ENV: 'production' },
      instances: 1,
      autorestart: true,
      max_memory_restart: '512M',
    },
    {
      name: 'mjn-portal',
      cwd: '/var/www/mjn-health/apps/portal',
      script: 'node',
      args: 'node_modules/next/dist/bin/next start -p 3002',
      env_production: { NODE_ENV: 'production' },
      instances: 1,
      autorestart: true,
      max_memory_restart: '512M',
    },
    {
      name: 'mjn-partner',
      cwd: '/var/www/mjn-health/apps/partner',
      script: 'node',
      args: 'node_modules/next/dist/bin/next start -p 3003',
      env_production: { NODE_ENV: 'production' },
      instances: 1,
      autorestart: true,
      max_memory_restart: '512M',
    },
    {
      name: 'mjn-admin',
      cwd: '/var/www/mjn-health/apps/admin',
      script: 'node',
      args: 'node_modules/next/dist/bin/next start -p 3004',
      env_production: { NODE_ENV: 'production' },
      instances: 1,
      autorestart: true,
      max_memory_restart: '512M',
    },
  ],
};
