export type TimelineStep = {
  step: string;
  label: string;
  detail: string;
};

export type Story = {
  slug: string;
  name: string;
  fullName?: string;
  profession: string;
  from: string;
  to: string;
  pathway: string;
  duration: string;
  outcome: string;
  quote: string;
  rating: number;
  year: string;
  flag: string;
  photo?: string;
  fullStory: string[];
  timeline: TimelineStep[];
};

export const stories: Story[] = [
  {
    slug: 'constance-che',
    name: 'Constance Che A.',
    fullName: 'Constance Che Abongnueh Epse Afungchui',
    profession: 'Registered Nurse (DHA-Licensed)',
    from: 'Cameroon',
    to: 'Dubai, UAE',
    pathway: 'DHA Licensing',
    duration: '4 months',
    outcome: 'DHA-Licensed Registered Nurse, Dubai — passed DHA exam first attempt',
    quote:
      'My journey to becoming a DHA-licensed Registered Nurse was smooth and stress-free, all thanks to MJN. From the very beginning, they clearly explained every step of the process, and everything happened exactly as they said it would. My process began while I was still in Cameroon. Once my DataFlow report was ready, I traveled to Dubai, took the exam in the second week, and passed on my first attempt. They were more than just consultants — they felt like family. A special thank you to Mme Arrey — words truly fail to express my gratitude.',
    rating: 5,
    year: '2025',
    flag: '🇦🇪',
    photo: '/constanceche.webp',
    fullStory: [
      'Constance had the clinical record that the Dubai Health Authority required — years of registered nursing experience in Cameroon, documented and verifiable. What she lacked was a reliable guide through the DataFlow primary source verification process and the DHA licensing exam. Several colleagues had warned her that the process was opaque, slow, and unpredictable when navigated alone.',
      'From her first consultation with MJN, Constance noticed the difference. Every step of the process was mapped out in advance — DataFlow document requirements, likely verification timelines, the DHA exam format, and what to expect in Dubai itself. There were no surprises because MJN had done this many times before and communicated proactively at each stage.',
      'Her DataFlow report was completed from Cameroon. Once it cleared, Constance travelled to Dubai with a clear plan already in place. She sat the DHA licensing exam in her second week in Dubai and passed on her first attempt. The entire journey — from first consultation to licence in hand — took four months.',
      'Constance singles out Mme Arrey by name for the quality of personal attention she received throughout. "They were more than just consultants — they felt like family," she says. "A special thank you to Mme Arrey — words truly fail to express my gratitude."',
    ],
    timeline: [
      { step: '1', label: 'Free consultation', detail: 'Eligibility assessed, DHA pathway mapped, DataFlow document checklist provided' },
      { step: '2', label: 'DataFlow submission', detail: 'All credential documents gathered and submitted for primary source verification — managed entirely from Cameroon' },
      { step: '3', label: 'DataFlow report cleared', detail: 'MJN coordinated with DataFlow case officers throughout; report approved without delays' },
      { step: '4', label: 'Pre-departure briefing', detail: 'Travel logistics, Dubai arrival plan, and DHA exam scheduling confirmed in advance' },
      { step: '5', label: 'DHA exam — week 2 in Dubai', detail: 'Sat the DHA licensing exam in the second week after arrival; passed on first attempt' },
      { step: '6', label: 'DHA licence issued', detail: 'Registered Nurse licence issued by Dubai Health Authority — ready to work' },
    ],
  },
  {
    slug: 'atangch-pascaline',
    name: 'Atangch Pascaline S.',
    fullName: 'Atangch Pascaline Sirrir',
    profession: 'Registered Nurse',
    from: 'Cameroon',
    to: 'United States',
    pathway: 'NCLEX Eligibility & State Board Application',
    duration: 'Multiple attempts resolved',
    outcome: 'NCLEX eligibility letter approved — after two previous rejections overturned by MJN',
    quote:
      'My cases are often extremely challenging, especially when I am at the final step and feeling stuck. MJN has consistently been the bridge that has carried me from the point of giving up to success. My eligibility letter application was returned twice and eventually rejected for not meeting the requirements. But when MJN submitted it, it was approved in no time. MJN, you have earned all my highest recommendations!',
    rating: 5,
    year: '2025',
    flag: '🇺🇸',
    photo: '/atangchpascaline.webp',
    fullStory: [
      'By the time Atangch found MJN, she had already spent considerable time — and hope — trying to secure her NCLEX eligibility letter independently. Her application to the state board had been returned twice and ultimately rejected on the grounds that it did not meet the requirements. She was, by her own account, at the point of giving up.',
      'The eligibility letter process for internationally educated nurses applying to US state boards is exacting. Requirements vary by state, the documentation standards are specific, and a single submission gap can result in rejection without clear guidance on what exactly needs to be fixed. Atangch had encountered this barrier twice.',
      'MJN reviewed her case in full, identified exactly what the state board needed, and submitted a clean, complete application. The approval came quickly — with no further queries or returns. The same application that had been rejected twice was now approved.',
      'Atangch\'s story illustrates one of MJN\'s most consistent strengths: taking on cases that have already failed elsewhere. "MJN has consistently been the bridge that has carried me from the point of giving up to success," she says. Her NCLEX eligibility is confirmed and her US nursing pathway is open.',
    ],
    timeline: [
      { step: '1', label: 'Case review', detail: 'MJN reviewed all prior rejections to identify the exact documentation gaps the state board had flagged' },
      { step: '2', label: 'Application rebuild', detail: 'Complete eligibility letter application restructured to meet state board requirements precisely' },
      { step: '3', label: 'Submission', detail: 'Clean, complete submission made on Atangch\'s behalf — no gaps or ambiguities' },
      { step: '4', label: 'Eligibility letter approved', detail: 'Approved with no further queries — same board that had rejected twice before' },
      { step: '5', label: 'NCLEX pathway open', detail: 'Authorisation to Test issued; NCLEX preparation underway' },
    ],
  },
  {
    slug: 'jeffrey-asiedu',
    name: 'Jeffrey Asiedu',
    fullName: 'Jeffrey Asiedu',
    profession: 'Registered Nurse (BSN, RN, USRN, DOH-RN)',
    from: 'Ghana',
    to: 'UAE & United States',
    pathway: 'DOH Licensing + NCLEX-RN',
    duration: 'End-to-end mentorship',
    outcome: 'DOH-Licensed RN in UAE + NCLEX-RN passed — dual international licensure',
    quote:
      'My journey with MJN Consulting has been truly remarkable. They played a pivotal role in my quest to become an international nurse, providing the support and guidance I needed to obtain my RN licence in the UAE with ease. My association with MJN did not end there — they continued to mentor me throughout my NCLEX journey, from the very beginning to the final steps. Thanks to their immense support and expertise, I successfully passed the NCLEX exam. Working with MJN Consulting has been an absolute pleasure.',
    rating: 5,
    year: '2025',
    flag: '🇦🇪',
    photo: '/jeffreyasiedu.webp',
    fullStory: [
      'Jeffrey came to MJN with a clear ambition: international registration in two of the most competitive nursing markets in the world — the UAE and the United States. For a Ghanaian nurse, achieving dual licensure across both regulatory systems requires navigating two entirely different frameworks, each with its own documentation requirements, examination formats, and timelines.',
      'MJN started with the UAE pathway. Jeffrey obtained his DOH (Department of Health, Abu Dhabi) licence — a process that includes DataFlow credential verification, a licensing examination, and employer matching. Throughout, MJN managed the documentation and kept the process moving.',
      'After his UAE registration was in place, Jeffrey\'s engagement with MJN continued. Rather than treat the NCLEX as a separate, unrelated process, MJN guided him through from the beginning — CGFNS credential evaluation, state board eligibility, exam preparation, and finally the NCLEX-RN itself. He passed.',
      'Jeffrey now holds credentials recognised in both the UAE (DOH-RN) and the United States (USRN) — a rare dual-licensure achievement that significantly expands his career options globally. "My association with MJN did not end there," he notes. "They continued to mentor me throughout my NCLEX journey, from the very beginning to the final steps."',
    ],
    timeline: [
      { step: '1', label: 'Consultation & pathway planning', detail: 'Dual pathway (UAE DOH + US NCLEX) mapped; sequencing strategy agreed' },
      { step: '2', label: 'DataFlow verification', detail: 'Ghanaian credentials submitted for primary source verification' },
      { step: '3', label: 'DOH licence — UAE', detail: 'DOH licensing exam passed; Registered Nurse licence issued for Abu Dhabi' },
      { step: '4', label: 'CGFNS evaluation', detail: 'US credential evaluation initiated; state board selected; eligibility application submitted' },
      { step: '5', label: 'NCLEX preparation', detail: 'Personalised study plan; exam prep mentorship from MJN throughout' },
      { step: '6', label: 'NCLEX-RN passed', detail: 'US Registered Nurse (USRN) — dual international licensure confirmed' },
    ],
  },
  {
    slug: 'vonvog-langmia',
    name: 'Vonvog Langmia N.',
    fullName: 'Vonvog Langmia Njei',
    profession: 'Registered Nurse (BSN, RN, USRN, DOH-RN)',
    from: 'Cameroon',
    to: 'UAE',
    pathway: 'DataFlow Verification + DOH Licensing',
    duration: 'Extended — MJN stayed committed throughout',
    outcome: 'DOH-Licensed Registered Nurse, UAE — despite delays and DataFlow setbacks',
    quote:
      'I am writing to express my heartfelt appreciation to MJN and Ma\'am Arrey for your exceptional patience, unwavering support, and diligent follow-up, which ultimately led to my success. I vividly recall the challenges — the delays, the frustrations, and my failure to respond promptly to the DataFlow verification process. Despite these hurdles, you remained steadfast and committed. May God continue to bless your team with the spirit of dedication.',
    rating: 5,
    year: '2025',
    flag: '🇦🇪',
    photo: '/vonvonglangmia.webp',
    fullStory: [
      'Vonvog\'s story is not one of a smooth, linear process — and that is precisely why it matters. His DataFlow verification was marked by delays, communication gaps, and periods where the process stalled. By his own account, there were times he did not respond promptly to DataFlow\'s requests, which introduced additional setbacks into an already extended timeline.',
      'Through all of it, MJN — and Mme Arrey specifically — stayed on the case. Every follow-up that needed chasing was chased. Every window that opened was used. The patience and persistence were not passive; they were active, structured engagement across an extended timeline.',
      'The DOH licence was eventually issued. Vonvog is now a licensed Registered Nurse in the UAE — an outcome that required his team to hold the course through obstacles that would have ended the process for a client without dedicated professional support.',
      '"I vividly recall the challenges — the delays, the frustrations, and my failure to respond promptly," Vonvog writes. "Despite these hurdles, you remained steadfast and committed." His story is a reminder that the hardest cases are often the ones where the value of professional representation is highest.',
    ],
    timeline: [
      { step: '1', label: 'Consultation', detail: 'DOH pathway assessed; DataFlow document checklist prepared for Cameroon credentials' },
      { step: '2', label: 'DataFlow submission', detail: 'Initial submission made; active follow-up communication began' },
      { step: '3', label: 'Verification setbacks', detail: 'Delays encountered — MJN maintained active follow-up throughout, managing communication with DataFlow on Vonvog\'s behalf' },
      { step: '4', label: 'DataFlow report cleared', detail: 'Primary source verification completed after extended engagement' },
      { step: '5', label: 'DOH licensing exam', detail: 'Exam sat and passed following DataFlow clearance' },
      { step: '6', label: 'DOH licence issued', detail: 'Registered Nurse licence — UAE (Abu Dhabi / Department of Health)' },
    ],
  },
  {
    slug: 'tita-louis',
    name: 'Tita M. Louis',
    fullName: 'Tita M. Louis',
    profession: 'Staff Nurse (DOH-Licensed)',
    from: 'Cameroon',
    to: 'Abu Dhabi, UAE',
    pathway: 'DOH Licensing + Job Placement',
    duration: 'Full-service from Cameroon to Abu Dhabi placement',
    outcome: 'DOH Staff Nurse, Abu Dhabi — DataFlow managed from Cameroon, welcomed on arrival, CV prepared',
    quote:
      'The benefits of MJN Healthcare Consulting cannot be overemphasised — her services are just the best. I was followed up through DataFlow, supported from my country, received on arrival, and helped to build a powerful CV for job search. The care and attention at every stage was something I had not experienced anywhere else.',
    rating: 5,
    year: '2025',
    flag: '🇦🇪',
    photo: '/titam.webp',
    fullStory: [
      'Tita chose a full-service engagement with MJN — not just licensing support, but the complete journey from Cameroon to employed and settled in Abu Dhabi. This meant DataFlow credential verification managed remotely, DOH licensing examination preparation, arrival logistics, CV preparation, and employer matching.',
      'The DataFlow process was handled entirely from Cameroon, removing the need for Tita to be in the UAE before her licence was ready. MJN maintained follow-up with the DataFlow verification body and kept the process moving through what is typically a multi-month procedure.',
      'On arrival in Abu Dhabi, MJN\'s team received Tita — practical on-the-ground support during the transition from home country to new country. This kind of continuity of care, from application through to arrival, is what distinguishes a comprehensive engagement from a transactional licensing service.',
      'With a professionally prepared CV in hand and employer connections through MJN\'s network, Tita secured a Staff Nurse position in Abu Dhabi. "The care and attention at every stage was something I had not experienced anywhere else," she says.',
    ],
    timeline: [
      { step: '1', label: 'Full-service engagement', detail: 'Scope agreed: DataFlow + DOH licensing + arrival support + job placement' },
      { step: '2', label: 'DataFlow — Cameroon', detail: 'All credentials gathered and submitted for primary source verification from Cameroon' },
      { step: '3', label: 'DOH licensing exam', detail: 'Exam preparation supported; licensing exam passed' },
      { step: '4', label: 'Arrival in Abu Dhabi', detail: 'MJN team present on arrival — onboarding to UAE life and employment market' },
      { step: '5', label: 'CV preparation', detail: 'Professional CV prepared for the UAE nursing job market' },
      { step: '6', label: 'Job placement', detail: 'Staff Nurse position secured — Abu Dhabi' },
    ],
  },
  {
    slug: 'sarah-danso',
    name: 'Sarah Danso',
    fullName: 'Sarah Danso',
    profession: 'Staff Nurse (DHA-Licensed)',
    from: 'Ghana',
    to: 'Dubai, UAE',
    pathway: 'DHA Licensing',
    duration: 'Full documentation support',
    outcome: 'DHA-Licensed Staff Nurse, Dubai — full documentation and placement support',
    quote:
      'MJN Healthcare Consulting has been the best link to me — contributing to my successful documentation and the assurance of arriving at my desired destination. Their patience, teamwork skills, and good communication is the best.',
    rating: 5,
    year: '2025',
    flag: '🇦🇪',
    photo: '/sarahdanso.webp',
    fullStory: [
      'For Sarah, the journey to Dubai began with the DHA documentation process — a sequence of credential submissions, primary source verifications, and licensing requirements that can be overwhelming to navigate without professional support. She engaged MJN to manage this process from Ghana.',
      'MJN handled the documentation comprehensively: assembling the credential file, ensuring every document met DHA standards, coordinating with DataFlow for primary source verification, and managing communication with the authority throughout the process.',
      'The outcome was a DHA Staff Nurse licence — and a placement in Dubai. Sarah arrived at her destination with the documentation complete and her position confirmed. "MJN has been the best link to me," she says, "contributing to my successful documentation and the assurance of arriving at my desired destination."',
      'She highlights three qualities specifically: patience, teamwork, and communication. These are the practical virtues that make the difference in a process that involves multiple parties — regulatory bodies, employers, and the client — all operating on different timelines and across different countries.',
    ],
    timeline: [
      { step: '1', label: 'Initial consultation', detail: 'DHA pathway assessed for Ghanaian nurse; full document checklist prepared' },
      { step: '2', label: 'Documentation assembly', detail: 'All credentials gathered, formatted to DHA standards, and reviewed for completeness' },
      { step: '3', label: 'DataFlow submission', detail: 'Primary source verification submitted and tracked' },
      { step: '4', label: 'DHA application', detail: 'Licensing application submitted following DataFlow clearance' },
      { step: '5', label: 'DHA licence issued', detail: 'Staff Nurse licence approved by Dubai Health Authority' },
      { step: '6', label: 'Placement in Dubai', detail: 'Job placement confirmed — Sarah arrived at her intended destination' },
    ],
  },
  {
    slug: 'richard',
    name: 'Richard',
    fullName: 'Richard',
    profession: 'Staff Nurse (DHA-Licensed)',
    from: 'Ghana',
    to: 'Dubai, UAE',
    pathway: 'DataFlow Verification + DHA Licensing',
    duration: 'Under 2 months',
    outcome: 'DHA-Licensed Staff Nurse, Dubai — licence secured in under 2 months',
    quote:
      'I thank MJN Healthcare Consulting so much for their immense contribution towards my DataFlow processing and licence application. Despite the difficulty, they stood by me from the beginning till I had my licence in less than two months.',
    rating: 5,
    year: '2025',
    flag: '🇦🇪',
    photo: '/richard.webp',
    fullStory: [
      'Richard\'s DHA licensing process was completed in under two months — a timeline that stands out even among MJN\'s faster cases. Achieving this required precision in documentation from the outset: no gaps, no ambiguity, and no back-and-forth with the licensing authority.',
      'DataFlow primary source verification is typically the longest step in the DHA process for internationally educated nurses. By assembling a complete, correctly formatted credential file from the start, MJN minimised the verification period and kept the application moving without delays.',
      '"Despite the difficulty," Richard notes — acknowledging that the process is not simple, even when it goes well. "They stood by me from the beginning till I had my licence in less than two months." The combination of professional representation and active follow-up at each stage compressed the timeline significantly.',
      'Richard is now a DHA-licensed Staff Nurse in Dubai — a result achieved in a fraction of the time many nurses spend on the process independently.',
    ],
    timeline: [
      { step: '1', label: 'Consultation', detail: 'DHA eligibility confirmed; fast-track document strategy agreed' },
      { step: '2', label: 'Complete file assembled', detail: 'All DataFlow and DHA documents prepared without gaps — reducing verification cycle time' },
      { step: '3', label: 'DataFlow submitted & tracked', detail: 'Active follow-up maintained throughout verification' },
      { step: '4', label: 'DHA application filed', detail: 'Licence application submitted immediately on DataFlow clearance' },
      { step: '5', label: 'DHA licence issued', detail: 'Staff Nurse, Dubai — under 2 months from engagement start' },
    ],
  },
  {
    slug: 'christelle-n',
    name: 'Christelle N.',
    profession: 'Registered Nurse',
    from: 'Yaoundé, Cameroon',
    to: 'Dubai, UAE',
    pathway: 'DHA Licensing',
    duration: '4 months',
    outcome: 'Staff Nurse, Dubai Hospital Group — AED 9,500/month + accommodation',
    quote:
      'I had tried the DataFlow process on my own for 8 months and got nowhere. MJN took over everything and had my DHA licence in 4 months. The difference was having someone who knew exactly what the case officers expected.',
    rating: 5,
    year: '2025',
    flag: '🇦🇪',
    fullStory: [
      'Christelle had spent eight months attempting the DataFlow process independently before engaging MJN. Eight months — and her case had not progressed. Without a clear understanding of what DataFlow case officers expected at each stage, the process had stalled in a cycle of incomplete submissions and unanswered queries.',
      'MJN took over the case entirely. Within four months of engagement, Christelle held her DHA licence. The difference, in her own words: "having someone who knew exactly what the case officers expected." This is institutional knowledge that cannot be acquired by reading guides online — it comes from processing dozens of cases through the same system.',
      'Christelle is now a Staff Nurse at a Dubai Hospital Group, earning AED 9,500 per month with accommodation provided. The total elapsed time from her first independent attempt to her DHA licence was over a year — but the time from MJN\'s involvement to her licence was four months. The gap is the cost of navigating without professional representation.',
    ],
    timeline: [
      { step: '1', label: '8 months — independent attempt', detail: 'DataFlow submission attempted without professional support; no progress made' },
      { step: '2', label: 'MJN engaged', detail: 'Full case review; previous submission gaps identified; DataFlow restarted with complete file' },
      { step: '3', label: 'DataFlow cleared', detail: 'Primary source verification completed within the engagement period' },
      { step: '4', label: 'DHA licence issued', detail: '4 months from MJN engagement start' },
      { step: '5', label: 'Job placement', detail: 'Staff Nurse, Dubai Hospital Group — AED 9,500/month + accommodation' },
    ],
  },
  {
    slug: 'dr-raymond-t',
    name: 'Dr. Raymond T.',
    profession: 'General Practitioner',
    from: 'Douala, Cameroon',
    to: 'London, UK',
    pathway: 'GMC Registration + NHS Placement',
    duration: '11 months',
    outcome: 'GP Registrar, NHS Foundation Trust — Band 7 equivalent',
    quote:
      'The GMC PLAB process is brutal if you do not know the system. My MJN consultant had gone through it personally as a Cameroonian doctor. She knew exactly which PLAB 2 centres to apply to, how to prepare my portfolio, and which trusts had active overseas recruitment. I would not have done it without MJN.',
    rating: 5,
    year: '2025',
    flag: '🇬🇧',
    fullStory: [
      'UK GMC registration for internationally qualified doctors involves two examinations — PLAB 1 and PLAB 2 — followed by a portfolio assessment and employment in an approved training post. For a Cameroonian doctor, this is a multi-stage, multi-year process if navigated without structured support.',
      'Dr. Raymond\'s MJN consultant had personal experience of the PLAB pathway as a Cameroonian medical professional — not theoretical knowledge, but lived experience of the same regulatory system. This made the advice concrete: which PLAB 2 assessment centres had shorter waiting times, how to structure a portfolio that met GMC expectations, which NHS trusts were actively recruiting from overseas, and how to present an application that would be competitive.',
      'The total timeline — from consultation to GP Registrar post in an NHS Foundation Trust — was 11 months. "The GMC PLAB process is brutal if you do not know the system," Dr. Raymond says. "I would not have done it without MJN." The failure rate at PLAB 2 for first-time candidates is significant, and the waiting period for a second attempt can be six months or more.',
    ],
    timeline: [
      { step: '1', label: 'GMC eligibility assessment', detail: 'Cameroonian medical degree and postgraduate experience assessed against GMC requirements' },
      { step: '2', label: 'PLAB 1 preparation', detail: 'Study plan developed; PLAB 1 written exam passed' },
      { step: '3', label: 'PLAB 2 preparation', detail: 'Clinical skills preparation with MJN consultant; assessment centre selected strategically' },
      { step: '4', label: 'PLAB 2 passed', detail: 'Clinical assessment passed; GMC full registration application submitted' },
      { step: '5', label: 'GMC registration granted', detail: 'Registered with the General Medical Council' },
      { step: '6', label: 'NHS placement', detail: 'GP Registrar, NHS Foundation Trust — Band 7 equivalent, London' },
    ],
  },
  {
    slug: 'patience-a',
    name: 'Patience A.',
    profession: 'Registered Nurse',
    from: 'Kumba, Cameroon',
    to: 'Dublin, Ireland',
    pathway: 'NMBI Registration + Critical Skills Permit',
    duration: '8 months',
    outcome: 'Staff Nurse, HSE Dublin — husband and two children now in Ireland',
    quote:
      'What MJN understood that I did not was that the family piece matters as much as the job. My consultant mapped the Critical Skills permit implications for my husband from the very first call. He is now working in Dublin without needing a separate permit. The whole family moved together.',
    rating: 5,
    year: '2024',
    flag: '🇮🇪',
    fullStory: [
      'Patience\'s story is one of the most complete outcomes in MJN\'s casebook — not just a nursing licence and a job, but an entire family relocated and settled in Dublin. From Kumba, Cameroon to HSE Staff Nurse in eight months, with her husband and two children now in Ireland.',
      'The detail that sets this case apart is the family planning dimension. Most licensing services are narrowly focused on the candidate. MJN\'s consultant mapped the Critical Skills Employment Permit implications for Patience\'s husband during the very first consultation call — before a document had been submitted or a fee had been paid.',
      'Under Irish immigration rules, a Critical Skills Employment Permit holder\'s spouse can work in Ireland without needing to obtain a separate permit. By ensuring Patience\'s placement was under a Critical Skills permit rather than a General Employment Permit, her husband was able to work immediately on arrival — a difference that significantly changes the family\'s financial position in the critical early months of relocation.',
      '"What MJN understood that I did not was that the family piece matters as much as the job," Patience says. That understanding — applied from the first call — is the kind of advisory depth that distinguishes specialist consulting from document processing.',
    ],
    timeline: [
      { step: '1', label: 'Consultation — family plan included', detail: 'NMBI pathway mapped; Critical Skills permit strategy for husband identified on first call' },
      { step: '2', label: 'NMBI application', detail: 'Nursing and Midwifery Board of Ireland registration application submitted with full document file' },
      { step: '3', label: 'NMBI registration granted', detail: 'Registered Nurse status confirmed by NMBI' },
      { step: '4', label: 'Job offer — HSE Dublin', detail: 'HSE Staff Nurse position secured under Critical Skills Employment Permit' },
      { step: '5', label: 'Permits & relocation', detail: 'Critical Skills permit issued; husband\'s work authorisation confirmed under spousal rules' },
      { step: '6', label: 'Full family in Dublin', detail: 'Patience, husband, and two children relocated to Dublin — all within 8 months of first consultation' },
    ],
  },
  {
    slug: 'blaise-k',
    name: 'Blaise K.',
    profession: 'ICU Nurse',
    from: 'Bafoussam, Cameroon',
    to: 'Abu Dhabi, UAE',
    pathway: 'DOH / HAAD Licensing',
    duration: '5 months',
    outcome: 'ICU Staff Nurse, Abu Dhabi Teaching Hospital — AED 11,000/month',
    quote:
      'I specifically wanted Abu Dhabi because of the DOH hospitals and the salary bands. My consultant knew the difference in requirements between DHA and DOH — most advisors I had spoken to did not. That specificity made all the difference.',
    rating: 5,
    year: '2025',
    flag: '🇦🇪',
    fullStory: [
      'Blaise arrived at MJN with a specific goal: Abu Dhabi, not Dubai. This distinction matters because the UAE\'s healthcare licensing authorities are split by emirate — DHA covers Dubai, while DOH covers Abu Dhabi. The examination requirements, fees, and recognition differ between the two authorities, and the salary bands in Abu Dhabi\'s government teaching hospitals are typically higher.',
      'Most advisors Blaise had spoken to before MJN did not know the practical difference between DHA and DOH requirements. MJN\'s consultant did — and guided Blaise through the DOH pathway specifically, avoiding the error of preparing for the wrong examination or submitting credentials to the wrong authority.',
      'As an ICU nurse with specialised clinical experience, Blaise was aiming for a position in a government teaching hospital — the type of facility where DOH licensing is required and where nursing salaries can reach AED 11,000 per month or above. That outcome was achieved in five months.',
      '"That specificity made all the difference," Blaise says. The difference between DHA and DOH is a fact any guide will tell you. Knowing what that difference means in practice — which exams, which pathways, which employers — is what professional consulting delivers.',
    ],
    timeline: [
      { step: '1', label: 'DOH pathway confirmed', detail: 'Abu Dhabi target confirmed; DOH (not DHA) requirements explained and agreed' },
      { step: '2', label: 'DataFlow — ICU specialty', detail: 'Credential verification submitted with ICU specialty documentation' },
      { step: '3', label: 'DOH licensing exam', detail: 'Prepared for and sat the DOH examination; passed' },
      { step: '4', label: 'DOH licence issued', detail: 'ICU Nurse licence — Department of Health, Abu Dhabi' },
      { step: '5', label: 'Job placement', detail: 'ICU Staff Nurse, Abu Dhabi Teaching Hospital — AED 11,000/month' },
    ],
  },
  {
    slug: 'sandra-o',
    name: 'Sandra O.',
    profession: 'Pharmacist',
    from: 'Lagos, Nigeria',
    to: 'Sharjah, UAE',
    pathway: 'MOH Licensing',
    duration: '3.5 months',
    outcome: 'Clinical Pharmacist, Private Hospital Group — MOH licence (Northern Emirates)',
    quote:
      'I had no idea which UAE authority to apply to for pharmacy. DHA, DOH, MOH — the differences were completely unclear to me. My consultant explained it in 10 minutes and had me on the right track immediately. The MOH exam was harder than I expected but the study plan helped.',
    rating: 5,
    year: '2024',
    flag: '🇦🇪',
    fullStory: [
      'Sandra\'s first question to MJN was the right one: "Which UAE licensing authority do I apply to?" For pharmacists, this is not obvious. The UAE\'s three main healthcare regulatory bodies — DHA (Dubai), DOH (Abu Dhabi), and MOH (Ministry of Health, covering the Northern Emirates including Sharjah) — each licence pharmacy practice in their jurisdiction. The right answer depends on where you intend to work.',
      'Sandra\'s target was Sharjah. That meant MOH — not DHA, not DOH. Her MJN consultant explained the distinction in the first consultation and had her on the correct pathway immediately, avoiding the wasted months that come from preparing for the wrong examination or approaching the wrong authority.',
      'The MOH licensing examination for pharmacists is rigorous. Sandra found it harder than expected — but she had a structured study plan from MJN that targeted the specific competencies the MOH exam tests. She passed, and her licence was issued within 3.5 months of engaging MJN.',
      'Sandra is now a Clinical Pharmacist with a private hospital group in Sharjah. The combination of clear pathway guidance and exam-specific preparation compressed what is often a six-month-plus process into 3.5 months.',
    ],
    timeline: [
      { step: '1', label: 'Authority selection', detail: 'Sharjah target confirmed; MOH (not DHA or DOH) identified as correct licensing pathway for Northern Emirates' },
      { step: '2', label: 'DataFlow — pharmacy credentials', detail: 'Nigerian pharmacy credentials submitted for primary source verification' },
      { step: '3', label: 'MOH exam preparation', detail: 'Structured study plan focused on MOH pharmacy examination competencies' },
      { step: '4', label: 'MOH exam passed', detail: 'Clinical pharmacy licensing examination — first attempt' },
      { step: '5', label: 'MOH licence issued', detail: 'Clinical Pharmacist licence — Ministry of Health, UAE (Northern Emirates)' },
      { step: '6', label: 'Placement in Sharjah', detail: 'Clinical Pharmacist, Private Hospital Group, Sharjah' },
    ],
  },
  {
    slug: 'nurse-fatoumata-d',
    name: 'Nurse Fatoumata D.',
    profession: 'Midwife',
    from: 'Conakry, Guinea',
    to: 'London, UK',
    pathway: 'NMC Registration (Midwifery)',
    duration: '13 months',
    outcome: 'Band 6 Midwife, NHS Trust, Birmingham — full OSCE first attempt',
    quote:
      'The OSCE is where most midwives from West Africa fail. My consultant prepared me for the UK expectations specifically — how to document, how to communicate with the examiner, what the OSCE stations actually test. I passed first time. Two colleagues who tried without support failed and had to wait 6 months for a second slot.',
    rating: 5,
    year: '2025',
    flag: '🇬🇧',
    fullStory: [
      'NMC registration for internationally educated midwives includes a critical clinical assessment stage: the Objective Structured Clinical Examination, or OSCE. For West African midwives in particular, the OSCE has a high first-attempt failure rate — not because of clinical incompetence, but because of specific UK documentation conventions, communication expectations, and examination formats that differ significantly from training in Guinea or other West African countries.',
      'Fatoumata\'s MJN consultant prepared her for the OSCE specifically — not just for the clinical content, but for the UK way of conducting and documenting clinical assessments, the examiner communication style, and the precise station-by-station structure of the NMC OSCE. This preparation is distinct from general clinical revision.',
      'She passed on her first attempt. Two colleagues who went through the OSCE without professional support did not — and faced a six-month wait for their next available slot. In the NMC registration timeline, six months is not an administrative inconvenience; it is six months of delayed employment, delayed income, and delayed UK residency progression.',
      'Fatoumata is now a Band 6 Midwife in an NHS Trust in Birmingham — the Band 6 grade reflecting her clinical experience and the professional standing her NMC registration confers.',
    ],
    timeline: [
      { step: '1', label: 'NMC eligibility review', detail: 'Guinean midwifery qualification assessed against NMC Part 1 and Part 2 requirements' },
      { step: '2', label: 'NMC application submitted', detail: 'Full credential file submitted; NMC correspondence managed by MJN' },
      { step: '3', label: 'CBT preparation', detail: 'Computer-Based Test study plan; CBT passed' },
      { step: '4', label: 'OSCE preparation', detail: 'UK-specific clinical assessment preparation: documentation, examiner communication, station formats' },
      { step: '5', label: 'OSCE — first attempt pass', detail: 'Clinical examination passed; NMC full registration confirmed' },
      { step: '6', label: 'NHS placement', detail: 'Band 6 Midwife, NHS Trust, Birmingham' },
    ],
  },
  {
    slug: 'jean-marc-e',
    name: 'Jean-Marc E.',
    profession: 'Registered Nurse',
    from: 'Ngaoundéré, Cameroon',
    to: 'Houston, US',
    pathway: 'NCLEX-RN + EB-3 Visa Sponsor',
    duration: '18 months',
    outcome: 'RN, Texas Medical Center — EB-3 immigrant visa sponsored',
    quote:
      'The US process is long. MJN was honest about that from the start — including the EB-3 retrogression realities for Cameroonians. They helped me choose the right state board, prepared a clean CGFNS submission, and introduced me to three hospital systems. I chose the best offer. 18 months was realistic.',
    rating: 5,
    year: '2024',
    flag: '🇺🇸',
    fullStory: [
      'Jean-Marc\'s journey to the United States is one of MJN\'s longer engagements — 18 months from first consultation to employed Registered Nurse at the Texas Medical Center. The US nursing immigration pathway is genuinely long, and Jean-Marc knew this going in. What he needed was a realistic map, not optimistic timelines.',
      'MJN provided exactly that. The EB-3 immigrant visa pathway for nurses involves CGFNS credential evaluation, state board eligibility, the NCLEX-RN examination, employer sponsorship, and visa processing — each step with its own timeline, requirements, and risks. For Cameroonian nationals, EB-3 visa retrogression (the per-country backlog in immigrant visa availability) is a real consideration. MJN was upfront about this from the start.',
      'State board selection matters significantly in the US pathway. Different states have different processing times for internationally educated nurse applications, and the right choice can compress the overall timeline. MJN helped Jean-Marc select the appropriate state board and prepared a clean, complete CGFNS submission that moved through without delays.',
      'Three hospital systems were identified through MJN\'s network as active EB-3 sponsors for internationally educated nurses. Jean-Marc reviewed the offers and chose the best one. "18 months was realistic," he says. That honesty — from the very first call — is what enabled him to plan accordingly and see the process through.',
    ],
    timeline: [
      { step: '1', label: 'Consultation — honest timeline set', detail: 'US pathway complexity explained; EB-3 retrogression realities discussed; realistic 18-month plan agreed' },
      { step: '2', label: 'State board selection', detail: 'Right US state board identified for Cameroonian credentials and processing time' },
      { step: '3', label: 'CGFNS evaluation', detail: 'Clean credential evaluation submission; approved without queries' },
      { step: '4', label: 'NCLEX-RN', detail: 'Exam preparation and NCLEX-RN passed' },
      { step: '5', label: 'Employer matching', detail: 'Three EB-3 sponsoring hospital systems introduced; best offer selected' },
      { step: '6', label: 'EB-3 visa & placement', detail: 'Immigrant visa sponsored; RN — Texas Medical Center, Houston' },
    ],
  },
  {
    slug: 'alvine-t',
    name: 'Alvine T.',
    profession: 'Physiotherapist',
    from: 'Yaoundé, Cameroon',
    to: 'Dublin, Ireland',
    pathway: 'CORU Registration (Physiotherapy)',
    duration: '9 months',
    outcome: 'Senior Physiotherapist, HSE Regional Hospital',
    quote:
      'CORU registration for allied health professionals is less documented than NMBI nurses. Finding accurate information was almost impossible online. MJN had done it before for physios — my consultant knew the exact documentation CORU needed and we had no back-and-forth queries. Smooth from start to finish.',
    rating: 5,
    year: '2025',
    flag: '🇮🇪',
    fullStory: [
      'CORU — the Health and Social Care Professionals Council — regulates physiotherapy registration in Ireland. Unlike NMBI for nurses, CORU registration for internationally educated allied health professionals is significantly less documented online. There is limited peer-to-peer guidance, fewer case studies, and less clarity on what CORU assessors look for in a submission from a Cameroonian physiotherapy qualification.',
      'Alvine found this out firsthand when she tried to research the CORU process independently. What she found — or rather did not find — was enough reliable, specific information to build a submission with confidence. That is when she contacted MJN.',
      'MJN had processed CORU registrations for physiotherapists before. The consultant assigned to Alvine\'s case knew the specific documentation CORU requires for Cameroonian-trained physiotherapists, how to present clinical hours, what the competency framework assessment involves, and what to include in the professional practice evidence. No back-and-forth queries from CORU. No requests for additional documents after submission.',
      'Alvine is now a Senior Physiotherapist at an HSE Regional Hospital in Dublin — a senior-grade appointment that reflects her clinical experience and a successful CORU registration completed in nine months from engagement to employment.',
    ],
    timeline: [
      { step: '1', label: 'CORU eligibility assessment', detail: 'Cameroonian physiotherapy degree and clinical hours assessed against CORU requirements' },
      { step: '2', label: 'Document preparation', detail: 'Full CORU submission file prepared — competency evidence, clinical hours, qualifications — to CORU standards' },
      { step: '3', label: 'CORU application submitted', detail: 'Complete submission; no back-and-forth queries from the regulator' },
      { step: '4', label: 'CORU registration granted', detail: 'Registered Physiotherapist — Health and Social Care Professionals Council, Ireland' },
      { step: '5', label: 'HSE placement', detail: 'Senior Physiotherapist, HSE Regional Hospital, Dublin — 9 months from engagement start' },
    ],
  },
];
